### ISSUE TITLE
Automatic generation of "xposed" module

### ISSUE THREAD

**Issue by mlinarev** [Captianrock/android_PV#25] opened 2016-02-19 16:39 UTC
As a user of the Java client, I would like to generate the module right after the APK/source code is analyzed. The GUI should have a button to start the ''xposed" module generation.

**Comment by eobie3** [comment] 2016-03-02 21:00
Currently generating a text file containing code using the output of Parser. Having trouble getting the package a parameter object resides in (Parser doesn't return the actual object, just a string representation).

**Comment by Captianrock** [comment] 2016-03-03 00:06
Just wanted to mention on here what we reiterated at the meeting, that you should also look into how build.gradle can compile an apk through general Xposed code.

**Comment by eobie3** [comment] 2016-03-04 01:56
Still working to find full object class. I believe the issue is with bindings, which are determined based on how the parser is configured. However, the project we are parsing seems to need to exist in the workspace. Looking for workaround. No guarantee this will give us the full name.

**Comment by eobie3** [comment] 2016-03-04 02:22
Apparently may need to use the Eclipse environment...
http://stackoverflow.com/questions/16692092/ijavaproject-without-eclipse-environment-in-jdt

**Comment by eobie3** [comment] 2016-03-04 05:12
Semi-working product. Does not include methods with non-primitive parameters. Breaks on a method in the module. But will print times for methods specified in code before the break. Produces output that team members can use to move the project forward. Will continue to improve and fix.

https://github.com/Captianrock/android_PV/commit/8452c28680507dec8951b402632b46ead2cd815f

**Comment by eobie3** [comment] 2016-03-10 04:34
What is the difference between class path and source path? The Internet is surprisingly unhelpful, or maybe I'm just not grasping it. What would they be for our project?

**Comment by mlinarev** [comment] 2016-03-10 13:35
Classpath is for libraries and compiled files (i.e., .jar and .class files); source path is for source code files (i.e., .java files)

**Comment by eobie3** [comment] 2016-03-10 14:40
Can you tell me what the classpath would be for this AlarmClock source code I've been using? (found here: https://github.com/Captianrock/android_PV/commit/91616094fb76bc8d5aac7a20de043b7cf9021888)  I understand that its source code would be in the /src files

**Comment by mlinarev** [comment] 2016-03-10 14:56
You set the class path to any folder you have locally with the libraries required to compile something. Thus, you have to identify what libraries are used by the app (by looking into the source code). If the app is using a library, then you have to locate the jar and copy it into a folder; that folder should be in the class path.

**Comment by eobie3** [comment] 2016-03-10 15:46
The issue is that to configure the parser, I have to pass in the class path for that app, and I can't find any jar files in the source code. Would I have to automate looking into the source code, finding the libraries, and pulling the jars from somewhere? I am not sure how I would do the latter.

**Comment by eobie3** [comment] 2016-03-10 15:48
I have thought of a potential workaround that will be inefficient but may work if that is too difficult.

**Comment by eobie3** [comment] 2016-03-11 21:24
I was able to configure the parser to give us the full name for parameters for the current running project. For other projects besides the current, the type name came up as "MISSING". I'll be switching back to the inefficient idea, which involves try blocks and matching the parameters with the import statements.

**Comment by eobie3** [comment] 2016-03-13 03:56
FINALLY figured out how to get full parameter name (I think - at least for the AlarmClock example). It will require all of the jar files needed to compile the program, so we might need the user to input any missing ones, unless there is a repository of jar files out there we can easily pull from. I will look into the user inputting jar files after I finish the module generation.

**Comment by mlinarev** [comment] 2016-03-13 16:28
Cool !!

**Comment by eobie3** [comment] 2016-03-29 01:39
Working for standard-issue classes, nested classes (multiple layers), anonymous classes, enum declarations, and constructors. I know what to do for constructors in nested static classes, still need to implement. Once that is done, the module will run for all of the AlarmKlock app without any errors (YAY!). Steps after implementing constructors in nested static classes will include getting it working for other apps (i.e., pulling the jar files) and compiling into an apk.

**Comment by eobie3** [comment] 2016-03-30 02:21
Fully functioning Xposed module for AlarmKlock app

154aaf0eb5aca2aa15b011b3330be904d3a7b1f5

**Comment by Captianrock** [comment] 2016-03-30 04:02
We will carry this issue down to the next sprint. The Xposed module proves to be much more work than expected, and Erin should be applauded for working this far into it.

**Comment by eobie3** [comment] 2016-04-03 20:50
Realized Xposed module is not working for given AlarmKlock source code. We are not hooking methods declared in objects instantiated within methods. Will need to reconfigure Parser to get parent chain and then work with ModuleBuilder to create the try blocks with the chain of anonymous classes.

**Comment by eobie3** [comment] 2016-04-18 15:23
Question regarding new apps: only the code in src/main/java should be analyzed, right? Can we assume that? The new apps have many more files than the original AlarmClock app we started testing with (only came with the true source code). I'm having trouble resolving the bindings for `GoogleDriveSyncProvider` in the `full` folder of CarReport. I'm not sure if it's because I'm missing a jar file or because it's not true source code.

**Comment by mlinarev** [comment] 2016-04-18 16:09
only the code in src/main/java should be analyzed, right? 
>> yes

 I'm having trouble resolving the bindings for GoogleDriveSyncProvider in the full folder of CarReport. I'm not sure if it's because I'm missing a jar file or because it's not true source code.
>> Probably you are missing a jar file. During the AST parsing there should be an error message saying what are the API calls it is not able to resolve the bindings.  Could you check what are the problematic bindings? In that case we can find the missing jar.  Anyway, the parser should be resilient, so if there are binding issues, i) there should be a message listing the issues, ii) those methods/classes should be excluded from the xposed module, and iii) the binding issues should not break the generation process.

**Comment by eobie3** [comment] 2016-04-18 17:28
It's unable to bind `AuthenticatorAddAccountActivity`, which lives in `main.java.me.kuehle.carreport.gui`.  `GoogleDriveSynchProvider`. I've pulled all the jar files noted in External Libraries, so I'm not sure what would be missing, especially because it's an object created by the app.

**Comment by eobie3** [comment] 2016-04-19 03:49
I'm unable to build an APK from CarReport's module - it claims that "code too large". The internet tells me that a java method can only be about 65kb. I'm not entirely sure what that translates to, but I'm guessing I've reached it. How should we fix this?

**Comment by eobie3** [comment] 2016-04-19 16:44
I fixed the code too large error by breaking the code into methods. I have another question regarding /src/main/java. For the most part (hopefully all), source code tends to follow that structure, but the decompiled APKs do not. When run on the phone, the module breaks for classes that don't live in /src/main/java (I assume that's why it's breaking for these classes). Should I put a try block around every find and hook method call in the module or only run through /src/main/java and not analyze any APKs that don't follow that structure?

**Comment by mlinarev** [comment] 2016-04-19 17:00
Decompiled APKs will not follow that structure. So you can do the following: for the case of APKs you can also ask the user (in the GUI) to provide you the main package; then you analyze only the classes inside that package.

**Comment by eobie3** [comment] 2016-04-19 22:51
^Will do.

Now trying to run this on the new apps and they have a much more complicated package structure. Example, `me.kuehle.carreport` is more or less the "main" package with inner packages such as `me.kuehle.carreport.data`, etc. Xposed will tell us which app (aka package) is loaded, but it never seems to load the inner ones. I try to access classes in the inner packages when Xposed loads the parent, but Xposed can't find these classes (likely because it's not digging into that nested package). How should I remedy this?

**Comment by eobie3** [comment] 2016-04-20 23:41
Closing because technically module is automatically generating. I have it fully working for the AlarmClock app and for two other smaller apps with a simple package structure. Still working on CarReport and MyExpenses

**Closed by eobie3** 2016-04-20 23:41 UTC
Labels: High Priority, New Feature
